[tools]
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.20.2" }
lune = { source = "filiptibell/lune", version = "0.6.6" }
rojo = { source = "rojo-rbx/rojo", version = "7.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.17.1" }
wally = { source = "UpliftGames/wally", version = "=0.3.1" }
