[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.0.2" }
selene = { source = "Kampfkarren/selene", version = "0.21" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.15.2" }
luau-analyze = { source = "JohnnyMorganz/luau-lsp", version = "1.14.2" }
darklua = { source = "seaofvoices/darklua", version = "0.8.0" }
