name: Tests

on: [push, pull_request]

env:
  FORCE_COLOR: 2

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v5

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        # luarocks install cluacov
        # luarocks install luacov-reporter-lcov

    - name: transpile code down to lua 5.1
      run: |
        cargo install --git https://gitlab.com/seaofvoices/darklua.git#v0.6.0
        darklua process src/ src/ --format retain-lines

    - name: Test
      run: |
        # lua -lluacov test/testez.lua
        # luacov -r lcov
